scheme: Pisces

darkmode: false
minify: true

custom_file_path:
  style: source/_data/styles.styl

favicon:
  small: /images/favicon-16x16-next.png
  medium: /images/favicon-32x32-next.png
  apple_touch_icon: /images/apple-touch-icon-next.png

footer:
  since: 2025
  icon:
    name: fa fa-heart
    animated: false
    color: "#808080"
  powered: true

menu:
  home: / || fa fa-home
  服务: /services/ || fa fa-briefcase
  案例: /cases/ || fa fa-diagram-project
  about: /about/ || fa fa-user
  archives: /archives/ || fa fa-archive
  RSS: /atom.xml || fa fa-rss

avatar:
  url: /images/avatar.gif
  rounded: true
  rotated: false

site_state: true
social:
  GitHub: https://github.com/fengcj717 || fab fa-github
  E-Mail: mailto:fengcj717@gmail.com || fa fa-envelope
social_icons:
  enable: true
  icons_only: false
  transition: false

post_meta:
  item_text: true
  created_at: true
  updated_at:
    enable: false
    another_day: true
  categories: true

symbols_count_time:
  separated_meta: true
  item_text_post: true
  item_text_total: false

tag_icon: true
read_more_btn: true
scrollpercent: true
back2top:
  enable: true
  sidebar: false
  scrollpercent: true

toc:
  enable: true
  number: true
  wrap: false
  expand_all: false
  max_depth: 4

codeblock:
  copy_button:
    enable: true
    show_result: true
    style: flat

local_search:
  enable: true
  trigger: auto
  top_n_per_article: 1
  unescape: false
  preload: false

comments:
  style: tabs
  active: false
  storage: false
  lazyload: false
  nav: null

pjax: true
motion:
  enable: true
  async: false
  transition:
    post_block: fadeIn
    post_header: fadeInDown
    post_body: fadeInDown
    coll_header: fadeInLeft
    sidebar: fadeInUp

seo: true
index_with_subtitle: false
exturl: false
